In [47]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

# Load data

X = pd.read_csv("../Outputs/pipeline1_train_preprocessed.csv")
y = pd.read_csv("../Outputs/pipeline1_train_target.csv")["SalePrice"]

# Original cleaned dataset
df_original = pd.read_csv("../Outputs/pipeline1_clean.csv")

# Working copy for feature engineering
df_fe = df_original.copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Original data shape:", df_original.shape)

print("\nData loaded successfully.")

Libraries imported successfully!
X shape: (1460, 208)
y shape: (1460,)
Original data shape: (1460, 77)

Data loaded successfully.

In [48]:
print("Starting number of features:", df_fe.shape[1])
# Creating Total Square Footage feature

df_fe["TotalSF"] = (
    df_fe["TotalBsmtSF"]
    + df_fe["1stFlrSF"]
    + df_fe["2ndFlrSF"]
)

print("TotalSF feature created successfully.")

# Preview
df_fe[["TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "TotalSF"]].head()

Starting number of features: 77
TotalSF feature created successfully.

   TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSF
0          856       856       854     2566
1         1262      1262         0     2524
2          920       920       866     2706
3          756       961       756     2473
4         1145      1145      1053     3343

In [49]:
# I Created Total Bathrooms feature

df_fe["TotalBathrooms"] = (
    df_fe["FullBath"]
    + 0.5 * df_fe["HalfBath"]
    + df_fe["BsmtFullBath"]
    + 0.5 * df_fe["BsmtHalfBath"]
)

print("TotalBathrooms feature created successfully.")

# Preview
df_fe[
    [
        "FullBath",
        "HalfBath",
        "BsmtFullBath",
        "BsmtHalfBath",
        "TotalBathrooms",
    ]
].head()

TotalBathrooms feature created successfully.

   FullBath  HalfBath  BsmtFullBath  BsmtHalfBath  TotalBathrooms
0         2         1             1             0             3.5
1         2         0             0             1             2.5
2         2         1             1             0             3.5
3         1         0             1             0             2.0
4         2         1             1             0             3.5

In [50]:
# Create Total Porch Area feature

df_fe["TotalPorchSF"] = (
    df_fe["OpenPorchSF"]
    + df_fe["EnclosedPorch"]
    + df_fe["3SsnPorch"]
    + df_fe["ScreenPorch"]
)

print("TotalPorchSF feature created successfully.")

df_fe[
    [
        "OpenPorchSF",
        "EnclosedPorch",
        "3SsnPorch",
        "ScreenPorch",
        "TotalPorchSF",
    ]
].head()


# Create Total Rooms feature
#maybe
df_fe["TotalRooms"] = (
    df_fe["TotRmsAbvGrd"]
    + df_fe["KitchenAbvGr"]
)

print("TotalRooms feature created successfully.")


df_fe[
    [
        "TotRmsAbvGrd",
        "KitchenAbvGr",
        "TotalRooms",
    ]
].head()


# Create Total Outdoor Area feature

df_fe["TotalOutdoorArea"] = (
    df_fe["WoodDeckSF"]
    + df_fe["OpenPorchSF"]
    + df_fe["EnclosedPorch"]
    + df_fe["3SsnPorch"]
    + df_fe["ScreenPorch"]
)

print("TotalOutdoorArea feature created successfully.")

df_fe[
    [
        "WoodDeckSF",
        "OpenPorchSF",
        "EnclosedPorch",
        "3SsnPorch",
        "ScreenPorch",
        "TotalOutdoorArea",
    ]
].head()

TotalPorchSF feature created successfully.
TotalRooms feature created successfully.
TotalOutdoorArea feature created successfully.

,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,TotalOutdoorArea
0,0,61,0,0,0,61
1,298,0,0,0,0,298
2,0,42,0,0,0,42
3,0,35,272,0,0,307
4,192,84,0,0,0,276

In [51]:
# Living area to lot area ratio

df_fe["LivingArea_to_LotArea"] = (
    df_fe["GrLivArea"] / df_fe["LotArea"]
)

print("LivingArea_to_LotArea feature created successfully.")

df_fe[
    [
        "GrLivArea",
        "LotArea",
        "LivingArea_to_LotArea",
    ]
].head()



#experiment
# df_fe["BasementRatio"] = (
#     df_fe["TotalBsmtSF"] / df_fe["TotalSF"]
# )

#experiment 
# df_fe["BasementRatio"] = (
#     df_fe["TotalBsmtSF"] / df_fe["TotalSF"]
# )

LivingArea_to_LotArea feature created successfully.

   GrLivArea  LotArea  LivingArea_to_LotArea
0       1710     8450               0.202367
1       1262     9600               0.131458
2       1786    11250               0.158756
3       1717     9550               0.179791
4       2198    14260               0.154137

In [52]:
# Created House Age feature

df_fe["HouseAge"] = df_fe["YrSold"] - df_fe["YearBuilt"]

print("HouseAge feature created successfully.")

df_fe[
    [
        "YrSold",
        "YearBuilt",
        "HouseAge",
    ]
].head()


# Created Remodel Age feature

df_fe["RemodelAge"] = df_fe["YrSold"] - df_fe["YearRemodAdd"]

print("RemodelAge feature created successfully.")

df_fe[
    [
        "YrSold",
        "YearRemodAdd",
        "RemodelAge",
    ]
].head()


# Created IsRemodeled feature

df_fe["IsRemodeled"] = (
    df_fe["YearBuilt"] != df_fe["YearRemodAdd"]
).astype(int)

print("IsRemodeled feature created successfully.")

df_fe[
    [
        "YearBuilt",
        "YearRemodAdd",
        "IsRemodeled",
    ]
].head()

#maybe
# df_fe["IsNewHouse"] = (df_fe["HouseAge"] <= 5).astype(int)

HouseAge feature created successfully.
RemodelAge feature created successfully.
IsRemodeled feature created successfully.

   YearBuilt  YearRemodAdd  IsRemodeled
0       2003          2003            0
1       1976          1976            0
2       2001          2002            1
3       1915          1970            1
4       2000          2000            0

In [53]:
# Create boolean features

df_fe["HasSecondFloor"] = (df_fe["2ndFlrSF"] > 0).astype(int)

df_fe["HasBasement"] = (df_fe["TotalBsmtSF"] > 0).astype(int)

df_fe["HasGarage"] = (df_fe["GarageArea"] > 0).astype(int)

df_fe["HasFireplace"] = (df_fe["Fireplaces"] > 0).astype(int)

df_fe["HasPool"] = (df_fe["PoolArea"] > 0).astype(int)

print("Boolean features created successfully.")

df_fe[
    [
        "HasSecondFloor",
        "HasBasement",
        "HasGarage",
        "HasFireplace",
        "HasPool",
    ]
].head()

Boolean features created successfully.

   HasSecondFloor  HasBasement  HasGarage  HasFireplace  HasPool
0               1            1          1             0        0
1               0            1          1             1        0
2               1            1          1             1        0
3               1            1          1             1        0
4               1            1          1             1        0

In [54]:
# Overall quality × living area
df_fe["Quality_x_Area"] = (
    df_fe["OverallQual"] * df_fe["GrLivArea"]
)

# Overall quality × total square footage
df_fe["Quality_x_TotalSF"] = (
    df_fe["OverallQual"] * df_fe["TotalSF"]
)

print("Interaction features created successfully.")

df_fe[
    [
        "OverallQual",
        "GrLivArea",
        "TotalSF",
        "Quality_x_Area",
        "Quality_x_TotalSF",
    ]
].head()

Interaction features created successfully.

   OverallQual  GrLivArea  TotalSF  Quality_x_Area  Quality_x_TotalSF
0            7       1710     2566           11970              17962
1            6       1262     2524            7572              15144
2            7       1786     2706           12502              18942
3            7       1717     2473           12019              17311
4            8       2198     3343           17584              26744

In [55]:
# Identify newly created features

new_features = [
    col for col in df_fe.columns
    if col not in df_original.columns
]

print("Original features :", len(df_original.columns))
print("New features      :", len(new_features))
print("Total features    :", len(df_fe.columns))

# List all new features

print("\nNew Features Created:\n")

for i, feature in enumerate(new_features, start=1):
    print(f"{i}. {feature}")


# Summary statistics of engineered features

df_fe[new_features].describe()

Original features : 77
New features      : 16
Total features    : 93

New Features Created:

1. TotalSF
2. TotalBathrooms
3. TotalPorchSF
4. TotalRooms
5. TotalOutdoorArea
6. LivingArea_to_LotArea
7. HouseAge
8. RemodelAge
9. IsRemodeled
10. HasSecondFloor
11. HasBasement
12. HasGarage
13. HasFireplace
14. HasPool
15. Quality_x_Area
16. Quality_x_TotalSF

,TotalSF,TotalBathrooms,TotalPorchSF,TotalRooms,TotalOutdoorArea,LivingArea_to_LotArea,HouseAge,RemodelAge,IsRemodeled,HasSecondFloor,HasBasement,HasGarage,HasFireplace,HasPool,Quality_x_Area,Quality_x_TotalSF
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,2567.048630,2.210616,87.084932,7.564384,181.329452,0.180590,36.547945,22.950000,0.476712,0.432192,0.974658,0.944521,0.527397,0.004795,9673.956164,16416.028767
std,821.714421,0.785399,105.190364,1.695244,156.656097,0.111914,30.250152,20.640653,0.499629,0.495550,0.157217,0.228992,0.499420,0.069100,5186.744876,8665.496074
min,334.000000,1.000000,0.000000,3.000000,0.000000,0.009459,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,334.000000
25%,2009.500000,2.000000,0.000000,6.000000,45.000000,0.119041,8.000000,4.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,5790.000000,10425.000000
50%,2474.000000,2.000000,48.000000,7.000000,164.000000,0.155687,35.000000,14.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,8820.000000,14718.000000
75%,3004.000000,2.500000,136.000000,8.000000,266.000000,0.195149,54.000000,41.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,12180.000000,20105.750000
max,11752.000000,6.000000,1027.000000,16.000000,1027.000000,0.945385,136.000000,60.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,56420.000000,117520.000000

In [56]:
# Load cleaned test dataset

test_df = pd.read_csv("../Outputs/pipeline1_test_clean.csv")

# Working copy for feature engineering
test_fe = test_df.copy()

print("Test data shape:", test_fe.shape)



# Aggregation Features


# Total Square Footage
test_fe["TotalSF"] = (
    test_fe["TotalBsmtSF"]
    + test_fe["1stFlrSF"]
    + test_fe["2ndFlrSF"]
)

# Total Bathrooms
test_fe["TotalBathrooms"] = (
    test_fe["FullBath"]
    + 0.5 * test_fe["HalfBath"]
    + test_fe["BsmtFullBath"]
    + 0.5 * test_fe["BsmtHalfBath"]
)

# Total Porch Area
test_fe["TotalPorchSF"] = (
    test_fe["OpenPorchSF"]
    + test_fe["EnclosedPorch"]
    + test_fe["3SsnPorch"]
    + test_fe["ScreenPorch"]
)

# Total Rooms
test_fe["TotalRooms"] = (
    test_fe["TotRmsAbvGrd"]
    + test_fe["KitchenAbvGr"]
)

# Total Outdoor Area
test_fe["TotalOutdoorArea"] = (
    test_fe["WoodDeckSF"]
    + test_fe["OpenPorchSF"]
    + test_fe["EnclosedPorch"]
    + test_fe["3SsnPorch"]
    + test_fe["ScreenPorch"]
)



# Ratio Features


# Living Area to Lot Area
test_fe["LivingArea_to_LotArea"] = (
    test_fe["GrLivArea"] / test_fe["LotArea"]
)



# Temporal Features


# House Age
test_fe["HouseAge"] = (
    test_fe["YrSold"] - test_fe["YearBuilt"]
)

# Remodel Age
test_fe["RemodelAge"] = (
    test_fe["YrSold"] - test_fe["YearRemodAdd"]
)

# Is Remodeled
test_fe["IsRemodeled"] = (
    test_fe["YearBuilt"] != test_fe["YearRemodAdd"]
).astype(int)



# Boolean Features


test_fe["HasSecondFloor"] = (
    test_fe["2ndFlrSF"] > 0
).astype(int)

test_fe["HasBasement"] = (
    test_fe["TotalBsmtSF"] > 0
).astype(int)

test_fe["HasGarage"] = (
    test_fe["GarageArea"] > 0
).astype(int)

test_fe["HasFireplace"] = (
    test_fe["Fireplaces"] > 0
).astype(int)

test_fe["HasPool"] = (
    test_fe["PoolArea"] > 0
).astype(int)



# Interaction Features


# Overall Quality × Living Area
test_fe["Quality_x_Area"] = (
    test_fe["OverallQual"] * test_fe["GrLivArea"]
)

# Overall Quality × Total Square Footage
test_fe["Quality_x_TotalSF"] = (
    test_fe["OverallQual"] * test_fe["TotalSF"]
)



# Summary


test_new_features = [
    col for col in test_fe.columns
    if col not in test_df.columns
]

print("Original test features :", len(test_df.columns))
print("New features created   :", len(test_new_features))
print("Total test features    :", len(test_fe.columns))

print("\nNew Features Applied:\n")

for i, feature in enumerate(test_new_features, start=1):
    print(f"{i}. {feature}")

print("\nFeature Engineering applied to test dataset successfully.")

Test data shape: (1459, 76)
Original test features : 76
New features created   : 16
Total test features    : 92

New Features Applied:

1. TotalSF
2. TotalBathrooms
3. TotalPorchSF
4. TotalRooms
5. TotalOutdoorArea
6. LivingArea_to_LotArea
7. HouseAge
8. RemodelAge
9. IsRemodeled
10. HasSecondFloor
11. HasBasement
12. HasGarage
13. HasFireplace
14. HasPool
15. Quality_x_Area
16. Quality_x_TotalSF

Feature Engineering applied to test dataset successfully.

In [57]:
#validation

train_cols = set(df_fe.columns)
test_cols = set(test_fe.columns)

# SalePrice train-də var, test-də yoxdur
train_cols.remove("SalePrice")

print("Train only columns:")
print(train_cols - test_cols)

print("\nTest only columns:")
print(test_cols - train_cols)

Train only columns:
set()

Test only columns:
set()

In [58]:
train_columns = list(df_fe.drop(columns="SalePrice").columns)
test_columns = list(test_fe.columns)

print(train_columns == test_columns)

True

In [59]:
print("Train Missing:", df_fe.isnull().sum().sum())
print("Test Missing :", test_fe.isnull().sum().sum())

Train Missing: 2422
Test Missing : 2497

In [60]:
print(np.isinf(df_fe.select_dtypes(include=np.number)).sum().sum())
print(np.isinf(test_fe.select_dtypes(include=np.number)).sum().sum())

0
0

In [61]:
print(sorted(new_features))

['HasBasement', 'HasFireplace', 'HasGarage', 'HasPool', 'HasSecondFloor', 'HouseAge', 'IsRemodeled', 'LivingArea_to_LotArea', 'Quality_x_Area', 'Quality_x_TotalSF', 'RemodelAge', 'TotalBathrooms', 'TotalOutdoorArea', 'TotalPorchSF', 'TotalRooms', 'TotalSF']

In [62]:
new_test_features = [
    col for col in test_fe.columns
    if col not in test_df.columns
]

print(sorted(new_test_features))

['HasBasement', 'HasFireplace', 'HasGarage', 'HasPool', 'HasSecondFloor', 'HouseAge', 'IsRemodeled', 'LivingArea_to_LotArea', 'Quality_x_Area', 'Quality_x_TotalSF', 'RemodelAge', 'TotalBathrooms', 'TotalOutdoorArea', 'TotalPorchSF', 'TotalRooms', 'TotalSF']

In [63]:
print(df_fe.shape)
print(test_fe.shape)

print(df_fe.columns[-16:])
print(test_fe.columns[-16:])

(1460, 93)
(1459, 92)
Index(['TotalSF', 'TotalBathrooms', 'TotalPorchSF', 'TotalRooms',
       'TotalOutdoorArea', 'LivingArea_to_LotArea', 'HouseAge', 'RemodelAge',
       'IsRemodeled', 'HasSecondFloor', 'HasBasement', 'HasGarage',
       'HasFireplace', 'HasPool', 'Quality_x_Area', 'Quality_x_TotalSF'],
      dtype='str')
Index(['TotalSF', 'TotalBathrooms', 'TotalPorchSF', 'TotalRooms',
       'TotalOutdoorArea', 'LivingArea_to_LotArea', 'HouseAge', 'RemodelAge',
       'IsRemodeled', 'HasSecondFloor', 'HasBasement', 'HasGarage',
       'HasFireplace', 'HasPool', 'Quality_x_Area', 'Quality_x_TotalSF'],
      dtype='str')

In [ ]:

# Feature Engineering Summary


print("=" * 50)
print("Feature Engineering Summary")
print("=" * 50)

print(f"Original train features : {df_original.shape[1]}")
print(f"New features created    : {len(new_features)}")
print(f"Total train features    : {df_fe.shape[1]}")
print(f"Total test features     : {test_fe.shape[1]}")
print(f"Training samples        : {df_fe.shape[0]}")
print(f"Test samples            : {test_fe.shape[0]}")

print(f"\nMissing values (train): {df_fe.isnull().sum().sum()}")
print(f"Missing values (test) : {test_fe.isnull().sum().sum()}")



# Save Feature Engineered Datasets


df_fe.to_csv(
    "../Outputs/pipeline1_train_feature_engineered.csv",
    index=False
)

test_fe.to_csv(
    "../Outputs/pipeline1_test_feature_engineered.csv",
    index=False
)

print("\nFeature engineered datasets saved successfully.")



# Save Feature List


with open("../Outputs/pipeline1_new_features.txt", "w") as f:

    f.write("New Features Created\n")
    f.write("====================\n\n")

    for i, feature in enumerate(new_features, start=1):
        f.write(f"{i}. {feature}\n")

print("Feature list saved successfully.")

==================================================
Feature Engineering Summary
==================================================
Original train features : 77
New features created    : 16
Total train features    : 93
Total test features     : 92
Training samples        : 1460
Test samples            : 1459

Missing values (train): 2422
Missing values (test) : 2497

Feature engineered datasets saved successfully.
Feature list saved successfully.

In [65]:
print(df_fe.columns[:5])
print(test_fe.columns[:5])

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea'], dtype='str')
Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea'], dtype='str')

In [66]:
print("Id in train:", "Id" in df_fe.columns)
print("Id in test :", "Id" in test_fe.columns)

Id in train: True
Id in test : True